[package]
name = "diagonalize"
version = "0.1.0"
authors = ["k-yamada <dixneufbhroarsns3mfcm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.27.1"
nalgebra-sparse = "0.3.0"
rand = "0.8.4"